// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Fallback for build-time (e.g. prisma generate in Docker); real value at runtime
    url: process.env.DATABASE_URL ?? "postgresql://build:build@localhost:5432/build",
  },
});
